class Program():
	def __init__(self, *args, ** kwargs):
		self.lang = input('what language?: ')
		self.version = input('what version')
		self.skill = input("what skill level?")

p1 = Program()

birthdays = {'Alice': 'Apr 1'. 'Bob':'Dec 12', 'Alex': 'Sep 28'}
while True:
	print("Enter a name: (blank to quit)")
	name = input()
	if nam == ' '
	break

	if name in birthdays:
		print(f'birthdays[name] + ' is the birthday of ' + name')
	else:
		print(' I do not have birthday information of ' + name)
		print('What is their birthday?')
		bday = input()
		

